version: '3.8'

services:
  db:
    image: mysql:8.4
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    user: root
    command: >
      bash -c "mkdir -p ./tmp/sockets && rails db:migrate && rm -f ./tmp/pids/server.pid && bundle exec puma -C ./config/puma.rb"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: yarn build
    volumes:
      - ./frontend/dist:/frontend/dist
    depends_on:
      - backend
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "ogami-app.com -> http://nginx:80"
      STAGE: "production"
    depends_on:
      - nginx
    volumes:
      - ./certs:/var/lib/https-portal
    restart: always

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  mysql-data:
  certs:
