services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/frontend
    command: >
      bash -c "yarn dev --host"
    ports:
      - "3000:3000"
