services:
  db:
    image: mysql:8.4
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    user: root
    command: >
      bash -c "mkdir -p ./tmp/sockets && rails db:migrate && rm -f ./tmp/pids/server.pid && bundle exec puma -C ./config/puma.rb"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: yarn build
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/frontend/dist:ro

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro

volumes:
  mysql-data:
